version: '3.8'

services:
  postgres:
    image: postgres:12.19
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./finq-back
    container_name: node_backend
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres_container/$POSTGRES_DB
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    depends_on:
      - postgres

  frontend:
    build: ./finq-front
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - backend

volumes:
  postgres_data: